### PR TITLE
Add in ability to limit and skip v2 routes containing large lists

### PR DESCRIPTION
**Pull request by RyanTheAllmighty**
Currently routes like https://meta.fabricmc.net/v1/versions/loader/1.14.2 return very long arrays.

I'd like to be able to skip and limit queries using query parameters.

This allows people to paginate or limit their queries to a single (or multiple) results.

Uses inbuilt validation from Javalin which will return errors when validation fails on the `limit` or `skip` parameters depending on their `accept` header. Example for `application/json`:

Capture

When no query parameters are provided, original functionality is retained.

### CODE REVIEW

**Comment by modmuss50** [comment]
Im out today, and dont have my keys on my laptop so I cannot update the live server until later. If I forget please poke me. Thanks 👍

**Comment by RyanTheAllmighty** [comment]
@modmuss50 any chance to deploy this yet? Server looks down from my end at the moment, hopefully unrelated

**Comment by modmuss50** [comment]
Server is up for me, but I forgot to update, will do it right now

**Comment by modmuss50** [comment]
Turns out it is down, there seems to be network issues, im looking into it.

**Comment by modmuss50** [comment]
Ok, seems to be working now https://meta.fabricmc.net/v2/versions/loader?limit=3&skip=10

Let me know if it goes down again as it seemed to just fixed it self.

**Comment by RyanTheAllmighty** [comment]
Yup looks good now. Thanks guys

**Pull request merged**
